### ISSUE TITLE
Consider adding new look for categories list

### ISSUE THREAD

**Issue by tangar76** [swissup/module-easycatalogimg#7]
![image](https://user-images.githubusercontent.com/13131588/63343974-ff0b1c00-c357-11e9-9626-ff48a82e8880.png)

Sample of CSS (LESS) code:

```less
& when (@media-common = true) {
    body .column.main .easycatalogimg {
        @__name-height: 25px;
        @__item__margin: 5px;
        @__item__padding: 5px;
        @__item__transition: .3s box-shadow;
        @__item__subcat__li__padding: 2px 10px;
        @__item__subcat__transition: .3s transform;

        border: none !important;
        margin: -@__item__margin;

        ul.list-subcategories {
            position: absolute;
            left: @__item__padding;
            right: @__item__padding;
            top: @__item__padding;
            bottom: @__item__padding;
            transform: translateY(100%);
            transition: @__item__subcat__transition;
            margin: 0;
            overflow: auto;
            padding: 0 0 @__name-height;

            li {
                padding: @__item__subcat__li__padding;
                margin: 0;
            }

            a {
                color: #fff;
                display: block;
            }
        }

        .parent-category.category-name {
            font-weight: bold;
            position: absolute;
            bottom: 0;
            margin: 0;
            left: @__item__padding;
            padding-bottom: @__item__padding;
            width: ~"calc(100% - 2 * @{__item__padding})";
            height: @__name-height;
            line-height: @__name-height;
            z-index: 1;
            background: #fff;

            a {
                color: #fff;
                display: block;
            }
        }

        .image {
            overflow: hidden;

            img {
                transition: @__item__subcat__transition;
            }
        }

        .easycatalogimg-grid li.item {
            border: solid 1px #efefef !important;
            overflow: hidden;
            position: relative;
            margin: @__item__margin;
            padding: @__item__padding @__item__padding (@__item__padding + @__name-height);
            transition: @__item__transition;

            &:hover {
                border: solid 1px #ccc;
                box-shadow: 1px 1px 5px #999;

                .list-subcategories {
                    transform: none;
                }

                .image img {
                    transform: scale(1.1);
                }
            }

            a:hover {
                text-decoration: none;
            }
        }

        .easycatalogimg-grid.easycatalogimg-cols-4 .item {
            width: ~"calc(25% - 2 * @{__item__margin})";
        }

        /**
         * Generate colors for category tiles
         */
        @__tile__color: #044d72 #b81d25 #6bb6ca #c93a72
                        #259291 #9dbc34 #c95226 #9f3370
                        #448c40 #6f1db8 #e2b34b #1d53b8;
        .__loop (0) {}
        .__loop (@index) when (@index > 0) {
            .item:nth-child(@{index}) {
                @__color: extract(@__tile__color, @index);
                .parent-category.category-name a {
                    background: @__color;
                }

                ul.list-subcategories {
                    background: fade(@__color, 20%);

                    li:hover {
                        background: @__color;
                    }
                }
            }
            .__loop (@index - 1);
        }

        .__loop(length(@__tile__color));
    }

}
```
